[package]
name = "ratatui-playground"
version = "0.1.0"
description = "A playground workspace for ratatui"
authors = ["JasterV <49537445+JasterV@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = "0.29.0"
